# File: microservices.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-build-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-build
  template:
    metadata:
      labels:
        app: client-build
    spec:
      containers:
      - name: client-build
        image: #yet to be decided
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: client-build-service
spec:
  selector:
    app: client-build
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: #Yet to be decided
        ports:
        - containerPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrape
  template:
    metadata:
      labels:
        app: scrape
    spec:
      containers:
      - name: scrape
        image: #yet to be pushed
        ports:
        - containerPort: 4002

---

apiVersion: v1
kind: Service
metadata:
  name: scrape-service
spec:
  selector:
    app: scrape
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: #yet to be pushed
        ports:
        - containerPort: 4003

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: user
        image: #yet to be pushed
        ports:
        - containerPort: 4004

---

apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004